### ISSUE TITLE
When you add a book to your owned list, instead of 'ok' it should say which book you added

### ISSUE THREAD

**Issue by iandioch** [iandioch/bookbot#9]
important for when you send messages without internet, or the bot goes down

**Comment by shepherdjay** [comment]
Can I try my hand at this one?

**Comment by iandioch** [comment]
You're right about the issues with testing, maybe it was a mistake adding the `good first issue` label way back when! I think changing `OwnBookView.message` before it is sent [on this line](https://github.com/iandioch/bookbot/blob/master/bookbot/view.py#L157) is all that is required, and the message should be changed back afterwards.

However, changing the class variable `message` is messy here. A much better solution would be adding an optional `message` parameter to [`View.show()`](https://github.com/iandioch/bookbot/blob/master/bookbot/view.py#L58), and if this parameter is replied, sending that instead of `cls.message`.

Implement whichever you like, but if you go with solution (1), please add a `# TODO: Refactor` comment next to the change.

Because of the issues with testing, and also the fact that the bot is not live, I'll just eyeball any changes you make and accept/request changes based on that. If in future when the bot is running again there turns out to be a problem, I'll fix it then.

Thanks for your contributions to this project!

**Comment by iandioch** [comment]
Edit to previous note: if you just use `View.show_info` instead of editing `View.show`, that's much better again.

**Comment by iandioch** [comment]
Edit again: maybe not, just do what feels right!
